version: 0.2

phases:
  install:
    commands:
      # install node 12
      - echo Installing Node 14...
      - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      # install dependencies
      - npm install
  build:
    commands:
      # build
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build